version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
        docker: 18  
    commands:
      - echo Installing ...
      - npm install
  pre_build:
    commands:
      - echo Logging in to Amazon ECR ...
      - $(aws ecr get-login --no-include-email --region ap-southeast-2)
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - echo Building the Docker image...
      - docker build -t parser_docker_image .
      - docker tag parser_docker_image:latest 766498452075.dkr.ecr.ap-southeast-2.amazonaws.com/parser_docker_image:latest
  post_build:
    commands:
      - echo Pushing the Docker images...
      - docker push 766498452075.dkr.ecr.ap-southeast-2.amazonaws.com/parser_docker_image:latest  
